name: Deploy Laravel Project on push to cpanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4 # Gunakan versi terbaru

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan dengan versi PHP cPanel kamu

      - name: Install Dependencies (Composer)
        run: composer install --no-dev --optimize-autoloader

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4 # Versi lebih stabil
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/bootstrap/**
            **/database/**
            **/public/**
            **/storage/**
            **/stubs/**
            **/tests/**
            **/vendor/**
            **.env
